name: example-environment
channels:
  - conda-forge
dependencies:
  - pip
  - pip:
   - python
   - numpy
   - psutil
   - toolz
   - matplotlib
   - dill
   - pandas
   - partd
   - bokeh
   - dask
   - seaborn
   - tdqm
   - sklearn
