name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - seaborn
  - tqdm
  - tensorflow
  - keras

  - pip
  - pip:
    - sklearn
    - os
