name: example-environment

channels:
  - conda-forge

dependencies:
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - tqdm
  - keras
  - imblearn
  - yellowbrick
  - warnings

  - pip
  - pip:
    - sklearn
